# Generated by Django 4.0.3 on 2022-03-23 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dogowner',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('phone_number', models.IntegerField()),
                ('dog_name', models.CharField(max_length=15)),
                ('dog_race', models.CharField(max_length=15)),
                ('dog_picture_url', models.CharField(max_length=1000)),
                ('dog_age', models.IntegerField()),
                ('dog_weight', models.FloatField()),
                ('dog_gender', models.CharField(choices=[('M', 'Male'),
                                                         ('F', 'Female'),
                                                         ('UN', 'Unknown')],
                                                default='M', max_length=2)),
                ('user', models.OneToOneField(null=True,
                                              on_delete=django.db.models.deletion.CASCADE,
                                              to=settings.AUTH_USER_MODEL)),
            ],
            managers=[
                ('DogOwners', django.db.models.manager.Manager()),
            ],
        ),
    ]
